### ISSUE TITLE
Feature request: skip on label

### ISSUE THREAD

**Issue by y-nk** [amannn/action-semantic-pull-request#126]
Would you be open to have a configurable array of tags for which, when found in PR, verification is skipped?

**Comment by y-nk** [comment]
In the project i'm working in, we have 2 types of PRs which are:

1. Task PR: for those, we enforce the title and squash the PR upon merging. It's typically JIRA ticket related.
2. Feature PRs: those, we don't enforce the title and rebase merge, so in the end the title doesn't matter. It's typically a group of task PR that we hold on the side until we get green light from other departments (mostly QA) that it can be put in staging.

Flow is normally:

1. Task PRs get squashed merged into Feature PR.
2. Feature PR get rebase merged into develop.
3. Release.

**Comment by amannn** [comment]
Thank you for your explanation. I think you should be able to handle that outside of the action with a config like:

```
if: ${{ !contains(github.event.pull_request.labels.*.name, 'Feature') }}
```

I haven't tested this and I'm not sure if it works exactly like this, but generally the Github Actions config should support this use case.

**Comment by y-nk** [comment]
oh you're right... i never think of writing these convenient ifs 🙏 thanks a lot!

**Comment by amannn** [comment]
Sure, you're welcome! 🙂

Maybe if you figure out the correct condition you can leave a comment here for other people which have a similar need!
