### ISSUE TITLE
Remove Usage of Github TOKEN

### ISSUE THREAD

**Issue by scolladon** [amannn/action-semantic-pull-request#139]
Hello,

Currently all the Pull Request done from a fork fail my job using this github action because it is not possible to have access to the Github Token I have set for my repo from their fork (which is a good thing from a security stand point).

I wonder if it could be possible to get rid of this github token usage ?
I have looked at some other github action doing similar thing and it seems not all of them requires this token
Exemple [here](https://github.com/wagoid/commitlint-github-action/blob/master/src/action.js)

Happy to help if needed to make this working

**Comment by amannn** [comment]
Hello @scolladon,

I'm afraid it's not possible to remove this token, there are a few places in the action that rely on an authenticated Github client that is initialized with the token:

https://github.com/amannn/action-semantic-pull-request/blob/60ee5322e18468b9e3bb23dd7d427a400b44d0f0/src/index.js#L8

Based on your description, you're probably using the `pull_request` event trigger? Possibly `pull_request_target` is what you're looking for. There's a [section about this in the README](https://github.com/amannn/action-semantic-pull-request#event-triggers).

**Comment by scolladon** [comment]
Thanks for your help !
I'll go this way (`pull_request_target`)
