### ISSUE TITLE
Bug: nonconventional commit message used in conjunction with merge commit

### ISSUE THREAD

**Issue by benelan** [amannn/action-semantic-pull-request#144]
First all, thanks for making this action! 

I noticed an issue where if there are two commits, one of them being a merge commit, GitHub uses the non-merge commit's message when squashing/merging the PR. We have `validateSingleCommit` enabled, but the action sees that scenario as two commits so it checks the PR title instead of commit message.

[Here is an example PR](https://github.com/Esri/calcite-components/pull/3612).

[And here is the commit after squashing/merging](https://github.com/Esri/calcite-components/commit/a01b9f7cb5281eecdcf33966951c132eebff723e).

It ended up using the first commit's message instead of the PR title. However the action assumed it would use the PR title. [Here is our workflow file](https://github.com/Esri/calcite-components/blob/master/.github/workflows/pr-semantic.yml).

**Comment by amannn** [comment]
Hi @benelan and thanks for the report,

this behaviour is related to merge commits and was addressed in [recent patch releases](https://github.com/amannn/action-semantic-pull-request/blob/master/CHANGELOG.md). If you upgrade to the latest version, you should be good.

If the problem persists, feel free to reopen!
