### ISSUE TITLE
Provide major version tags

### ISSUE THREAD

**Issue by kenji-miyake** [amannn/action-semantic-pull-request#151]
@amannn Hello, thank you for developing this useful project!

Is it possible to provide major version tags (v1, v2, v3, ...) as well? I think it's automatically done by using this action.
https://github.com/Actions-R-Us/actions-tagger

Thank you.

**Comment by amannn** [comment]
Hello @kenji-miyake and thanks for the request.

I haven't experimented with that yet. Would you be interested in setting this up and providing proof that it works as expected?

**Comment by kenji-miyake** [comment]
Yes, I'll try it in my fork repository and send a pull request.

**Comment by kenji-miyake** [comment]
I've tested.

Actually, I needed to edit (just click the `Update release` button without any changes) a release after it's published by `semantic-release` because [release events triggered by `GITHUB_TOKEN` probably cannot trigger another workflow event](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token).

@amannn Is this okay for you? It has a small manual task.

---

The following is the detailed information about my test.

Commit log:
https://github.com/kenji-miyake/action-semantic-pull-request/commits/master
![image](https://user-images.githubusercontent.com/31987104/148183819-75544abe-dbf6-4897-b683-c37cbcafe6de.png)

Action:
https://github.com/kenji-miyake/action-semantic-pull-request/actions

Result of tags:
https://github.com/kenji-miyake/action-semantic-pull-request/tags

**Comment by amannn** [comment]
Thanks a lot for your work!

> Actually, I needed to edit (just click the Update release button without any changes) a release after it's published by semantic-release because release events triggered by GITHUB_TOKEN probably cannot trigger another workflow event.

Right, that is already the case currently!

Would you like to send a PR with the adjustment?

**Comment by kenji-miyake** [comment]
Okay, thank you! Then I'll send a PR.
But I'm not sure what `the adjustment` means. What did you indicate?

**Comment by amannn** [comment]
By adjustment I meant the added workflow, just what you suggested in the PR! 🙂

**Comment by kenji-miyake** [comment]
Thank you very much! :smile: 
https://github.com/amannn/action-semantic-pull-request/releases/tag/v3

**Comment by amannn** [comment]
Worked flawlessly, thank you so much! 🙂
