### ISSUE TITLE
Make new single-commit PR validation optional

### ISSUE THREAD

**Issue by mowies** [amannn/action-semantic-pull-request#159]
The changes done by @kenji-miyake in #158 are a great addition, but I think they should be configurable through a flag/setting.

I have a few bot-created pull requests where the single commit message has more info that should stay there, but it's not important for the PR reviewer, so in this case I would like to keep the title simple but the commit message should still have more advanced info inside.

Here is an example: https://github.com/keptn/keptn/pull/6789

**Comment by amannn** [comment]
Ok, yes – sounds like a fair use case. @kenji-miyake Would you mind adding an opt-in flag like `validateSingleCommitMatchesPr` for the behaviour you've added?

**Comment by kenji-miyake** [comment]
No, I don't mind that, but I feel we can discuss it a bit more here.

Although I don't deny @mowies's use case, let me confirm:

- What if GitHub changes the specification of the squashed commit message?
  - In that case, the message will suddenly change from `build(deps): Update keptn/go-utils to 8717cd9293a5940fd4dd931b9ea1daf16258364e` to `build(deps): Auto-update go-utils to latest version`.
  - Is it acceptable for you?
- What is the reason for not writing the commit message like this?

```text
build(deps): Auto-update go-utils to latest version

Update keptn/go-utils to 8717cd9293a5940fd4dd931b9ea1daf16258364e
```

Anyway, I'll prepare a PR while waiting for the reply!

**Comment by kenji-miyake** [comment]
@amannn Regarding the CI, should I create `lint-pr-title-preview-validateSingleCommitMatchesPr.yml` or can I add an option to `lint-pr-title-preview-validateSingleCommit.yml`?

**Comment by amannn** [comment]
I think enabling the flag in the existing workflow should be fine. Thanks a lot!

**Comment by kenji-miyake** [comment]
@amannn How about this one?

```
When using "validateSingleCommit", even if you edit the PR title, the PR title is not used for the merge commit.

Also, since it cannot detect an error as long as the commit message is semantic, it's easy to commit this by mistake.

Enable this option to also validate if the PR title matches the commit title.
```

**Comment by kenji-miyake** [comment]
FYI: A new option, "Default to PR titles for squash merge commit messages".
https://github.blog/changelog/2022-05-11-default-to-pr-titles-for-squash-merge-commit-messages/
https://github.com/github/feedback/discussions/16271

**Comment by amannn** [comment]
Oh my god, that's fantastic. Thank you so much for sharing this @kenji-miyake! I'll add this to the docs.
