### ISSUE TITLE
show more information in check

### ISSUE THREAD

**Issue by rethab** [amannn/action-semantic-pull-request#163]
Hi,

this action currently shows a simple `Successful` message when the PR title was successfully validated like so:
![image](https://user-images.githubusercontent.com/2222044/155681163-0dabbb7a-3bc4-44a8-b07d-7b6b48a8799e.png)

However, I think GitHub API would allow us to show more information and we could actually indicate what type of change this PR title will lead to. So for example, when using a PR title `feat: foo`, the check could say `Successful: New Feature`.

Once that works, it would also be handy to look at PR descriptions and look for `BREAKING CHANGES`. I know the README says it only looks the PR title, but why not look at the description?

The problem is that [semantic-release does not support the exclamation mark](https://github.com/semantic-release/semantic-release/issues/2339). It would be nice if this action worked well with semantic release :)

**Comment by amannn** [comment]
Hi and thanks for opening this issue!

> However, I think GitHub API would allow us to show more information and we could actually indicate what type of change this PR title will lead to. So for example, when using a PR title feat: foo, the check could say Successful: New Feature.

I'd be open to showing a bit more details in the success message if we can keep it succinct. We have to keep in mind though that the user can customize the types and in this case we don't have anything more than the type itself. Also note that we can't assume what kind of release a given type will lead to.

> The problem is that semantic-release does not support the exclamation mark. It would be nice if this action worked well with semantic release :)

Are you saying that semantic-release dropped the support for detecting exclamation marks in the title? Because that's a feature this action is largely based on.

**Comment by rethab** [comment]
> Are you saying that semantic-release dropped the support for detecting exclamation marks in the title? Because that's a feature this action is largely based on.

I'm not sure if they dropped it, because I haven't been using it for long. What I can say is that it doesn't work now and the issue I linked above also seems to support that.

Here are some logs from one of my libraries (can't show full logs because this is not open source):

```
[6:51:45 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat!: remove obsolete fields (#10)
[6:51:45 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
```

**Comment by amannn** [comment]
That's quite interesting, thanks for sharing. I've left a comment in the linked thread. I guess for now an older version of `@semantic-release/commit-analyzer` might help – e.g. the one used in this repo is known to work.

I hope that this behaviour will be added back on the semantic-release side.

**Comment by amannn** [comment]
@rethab A maintainer from semantic-release has replied in regards to the exclamation point topic here: https://github.com/semantic-release/semantic-release/issues/2339#issuecomment-1058276297. I'm wondering what kind of preset you're using for semantic-release? Can you confirm that it's the conventional commits one?

If you have some more information, maybe you could join the discussion in the thread. I'm missing some context currently.

**Comment by rethab** [comment]
ah, sorry @amannn I think I was confused about the semantic release config. We do not use conventional commits, but just whichever is default (angular?). that's why it didn't work as expected.

Please feel free to close this ticket.

Sorry for the confusion caused.
