### ISSUE TITLE
Add config to disallow certain scopes

### ISSUE THREAD

**Issue by lquixada** [amannn/action-semantic-pull-request#176]
I'm the author of a public npm package called [cross-fetch](https://github.com/lquixada/cross-fetch). Every time a push is made on the `main` branch, the CI workflow is triggered. If the commit starts with `chore(release)`, this is the signal for CI to publish a release on npm and Github after all building, testing and linting is done. However if someone opens a PR with a title that starts with `chore(release)`, I'm not seeing a way to avoid the release. Would the maintainers consider adding a `disallowedScopes` config so users could avoid scopes such as `release`?

**Comment by amannn** [comment]
Do you enforce a certain convention for PRs or do you just want to disallow this particular prefix?

If you generally want to use scopes, you can define a list that doesn't contain the `release` scope. Or are the scopes arbitrary and you want to exclude a particular scope?

If the only thing you want to lint for is that the PR title doesn't start with `chore(release)` you might be better off with one of the alternative Github actions that validate the PR title based on a regex.

**Comment by lquixada** [comment]
According to the [conventional commit specs](https://www.conventionalcommits.org/en/v1.0.0/#specification), a scope can be any noun. So it's pretty broad. Defining a list of allowed scopes can be limiting.

However my specific need is just for the "release" word. As you mentioned a Github Action that validates PR title would certainly meet that requirement. The problem is it would mean adding an extra action to the pipeline, managing its config, updating its versions and monitoring security.

I opened this issue to check if `cross-fetch`'s pipeline could be slimmer by only using the `semantic-pull-request` action with a potential `disallowedScopes` option. If adding that option is not interesting to this project, I'll certainly consider using the action you've suggested!

**Comment by amannn** [comment]
I definitely see your point. I guess I'd be open to a `disallowScopes` config option (I removed the `d`, since we already have `requireScope`). Probably we should throw if this is configured together with `scopes`.

Would you be interested in contributing this feature?

**Comment by lquixada** [comment]
I'd be happy to but `cross-fetch` already takes up all my free time. That being said, feel free to close the issue if no contributors volunteers to work on this.

**Comment by amannn** [comment]
Sure, I understand. Let's leave the issue open for now then in case someone else is interested.

**Comment by jmosawy** [comment]
@amannn @lquixada I'll be working on it. I opened a draft PR to play around and make sure everything's fine.
