### ISSUE TITLE
Add outputs so this action can be composed

### ISSUE THREAD

**Issue by kunaltyagi** [amannn/action-semantic-pull-request#178]
Eg: post the expected pattern as a comment

**Comment by amannn** [comment]
Hello @kunaltyagi! 

I'm sorry, I don't understand the request. Can you elaborate in a bit more detail?

**Comment by kunaltyagi** [comment]
If the action fails, I wish to use another action to create a comment to help the user understand how the PR title should be formatted. Hopefully, this makes sense

**Comment by amannn** [comment]
Interesting, I see. Do you have some background on how that works?

**Comment by kunaltyagi** [comment]
Theres [this](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter=) via the shell. For using actions/core, there's [this](https://github.com/actions/toolkit/tree/main/packages/core#inputsoutputs=) API

**Comment by jthegedus** [comment]
[This Action](https://github.com/jef/conventional-commits-pr-action) performs what I think the OP is requesting. I think the notion of commenting examples or suggesting a title would be useful as I usually have to resolve failures of this Action by myself.

**Comment by amannn** [comment]
I see, thanks for the link! If you're interested in working on this, I'd be open to a contribution of this feature.
