### ISSUE TITLE
Abide by stricter constraints

### ISSUE THREAD

**Issue by andreilg** [amannn/action-semantic-pull-request#198]
A commit message such as `feat: Hello world.` passes this GitHub Action. However the [Angular convention](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#subject) that Conventional Commits is based on states:
> The subject contains a succinct description of the change:
> 
> use the imperative, present tense: "change" not "changed" nor "changes"
> don't capitalize the first letter
> no dot (.) at the end

I'm aware that Conventional Commits isn't as strict, but I see no reason to allow for variations of this kind since they undermine the goal of consistent commits.

**Comment by amannn** [comment]
I see your point, but I'm not sure how this action could validate against something like this? Also it's quite individual based on the team that uses the action I guess.

Some additional validation like having to start with a lowercase letter is available via `subjectPattern`. Does that help?

**Comment by andreilg** [comment]
> I see your point, but I'm not sure how this action could validate against something like this?

You could enable `subjectPattern: ^[^A-Z].*[^.]$` by default.

> Also it's quite individual based on the team that uses the action I guess.

Sure, but it's a convention and from what I've seen, almost everybody adheres to the Angular specification for subjects. People are free to use their own `subjectPattern` if they want to do it another way. However, having the possibility for such variability by default opens up the door for lots of inconsistent commits and undermines the point of this action altogether since the current defaults still require monitoring the commit messages no matter what convention you're using. This might not be an issue for small teams, but for open-source projects, there will always be inconsistency if allowed.

> Some additional validation like having to start with a lowercase letter is available via subjectPattern. Does that help?

It helps me personally but I was suggesting this as a default for your action since most people are just going to be using defaults and run into this issue at some point.

**Comment by amannn** [comment]
I see your point, but e.g. personally I don't adhere to the Angular specification. I try to strike a balance where the defaults help with the general use case. The reason why I created the action was to work well with tools like semantic-release that pick up the prefix types and I try to align the defaults with that use case. More validation is possible but a bit up to the consumer. If you need a special configuration across a number of repositories, you can wrap the action and the configuration into a new action.

> still require monitoring the commit messages no matter what convention you're using

I think that will always be the case.

**Comment by andreilg** [comment]
Fair enough. Thank you for hearing me out.
