### ISSUE TITLE
Regex support for scope

### ISSUE THREAD

**Issue by tomerleib** [amannn/action-semantic-pull-request#221]
**Is your feature request related to a problem? Please describe.**

Is it possible to provide scopes by a regex?
Our GH repo is connected to Jira, and each PR must be `fix(JIRA-123): threads`. 
I've tried using the action with specifying `JIRA` in the scope but the action failed since `JIRA-123` is not included.

**Describe the solution you'd like**

An option to provide a regex for scopes.

**Comment by rrundle-dave** [comment]
+1 
@tomerleib do you want to open a PR for this? If @amannn is accepting them?

**Comment by Eunanibus** [comment]
Just an FYI @amannn  - I didn't see this in the README and I had to hunt for it here. Might be worth updating the docs?
