### ISSUE TITLE
"type" in PR title should encompass all types of its commit messages

### ISSUE THREAD

**Issue by SvenStaehs** [amannn/action-semantic-pull-request#234]
**Is your feature request related to a problem? Please describe.**

In my project we enforce commit syntax for every commit in the PR with commitlint and also for PR title, then use semantic-release to create changelog for releases.  
I've seen PRs titled with "fix" that contain commits that add features, themselves properly marked as "feat", so no linter complains. 
 
PR gets squash-merged to main and semantic-release thinks this is just a fix and only bumps the patch version.

Even worse if someone introduces a breaking change and does not mention that in PR description, I haven't seen this in action but I would expect that means semantic-release no longer knows that there's been a breaking change.

**Describe the solution you'd like**

This action could parse the commits of the branch and fail if they conflict with the type of the title.  
e.g. if any commit is a feat, PR title must be feat.

Bonus: If any commit mentions a breaking change or deprecation, this should be included in PR description.

**Describe alternatives you've considered**

Thought about writing my own shell script that does the same with some simple regexes, but all the parsing work is already done here, so it would be a shame to waste it 😉

**Comment by amannn** [comment]
Hey, thanks for the question! This action currently doesn't aim to parse commits. [We had an exception](https://github.com/amannn/action-semantic-pull-request#legacy-configuration-for-validating-single-commits), but this is now considered legacy. If you happen to write a shell script, feel free to share it here in case other users find it helpful too! 🙂

**Comment by SvenStaehs** [comment]
entirely understandable stance to take 😉
