### ISSUE TITLE
node20 support and new release

### ISSUE THREAD

**Issue by MikeMcC399** [amannn/action-semantic-pull-request#239]
## Current situation

The latest release of this action [v5.2.0](https://github.com/amannn/action-semantic-pull-request/releases/tag/v5.2.0) runs under the deprecated `node16` version of Node.js

https://github.com/amannn/action-semantic-pull-request/blob/00282d63cda40a6eaf3e9d0cbb1ac4384de896e8/action.yml#L4-L6

Node.js `16` already entered into[ end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol) on Sep 11, 2023.

## Requested change

Please update the action to run under `node20` according to the GitHub announcement [GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) dated Sep 22, 2023.

See also [`runs` for JavaScript actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions).

## Benefit

According to GitHub's announcement all `node16` JavaScript actions will be forced to run under `node20` early in 2024. Proactively migrating, testing and releasing a new version of this action gives users the opportunity to migrate earlier than the forced migration and avoids any surprises that may be caused by any otherwise undiscovered incompatibility with `node20`.

**Comment by amannn** [comment]
Great point, thanks for bringing this up! Would you be interested in setting up a PR with the relevant change?

**Comment by MikeMcC399** [comment]
@amannn 

> Would you be interested in setting up a PR with the relevant change?

Thanks for your interest!

Unfortunately I don't have the history and experience in this repo, so I'm probably not the best person to be submitting a PR for this change. It looks like there are multiple changes which would be necessary and it's not simply a case of changing `action.yml` to refer to `node20` instead of `node16`.  Workflows are also running under the end-of-life Node.js `16` and these should probably be changed as well. It will probably take 6 months before GitHub forces the use of `node20`, so hopefully that should be enough time to prepare.
