### ISSUE TITLE
issue on MRPL website 

### ISSUE THREAD

**Issue by Rahulkumajr** [amannn/action-semantic-pull-request#241]
**Describe the bug**
On website footer bar email descripation are not properly as per the other website.
Website link :- https://www.mrpl.co.in/
Email Address are not properly aligment.
**To reproduce**
On Website footer bar 
Please include a reproduction repository and outline the steps that are needed to run into the issue.
1.Search on google **mrpl**  
**Expected behavior**
(Actual result :- [[mrplmlr[at]mrpl[dot]co[dot]in)]]   Screen short :- (https://prnt.sc/bqbm1LER3SuQ)
Expected result :- mrplmlr@mrp.co.in

**Comment by amannn** [comment]
Did you by chance comment on the wrong repo? Your inquiry doesn't seem related to this project as far as I can tell.

**Comment by Rahulkumajr** [comment]
ok My mistake

**Comment by Rahulkumajr** [comment]
**Describe the bug**
On our website 
A clear and concise description of what the bug is.
On Jan Aman Website Footer bar Twitter logo are not same as per live Twitter site.
**To reproduce**
 [](https://prnt.sc/UNVHRJ9_TSM0)
Please include a reproduction repository and outline the steps that are needed to run into the issue.
On Website Footer bar this issue.
**Expected behavior**
Logo image change as per Twitter site logo.
A clear and concise description of what you expected to happen.
https://prnt.sc/iOZBI0j9sOHw :- See Screen Short

**Comment by Rahulkumajr** [comment]
Describe the bug
On our website
A clear and concise description of what the bug is.
On Jan Aman Website Footer bar Twitter logo are not same as per live Twitter site.
To reproduce

Please include a reproduction repository and outline the steps that are needed to run into the issue.
On Website Footer bar this issue.
Expected behavior
Logo image change as per Twitter site logo.
A clear and concise description of what you expected to happen.
https://prnt.sc/iOZBI0j9sOHw :- See Screen Short

**Comment by Rahulkumajr** [comment]
Ok Sir I Have Upadte Ticket Releted Project please Check.

**Comment by Rahulkumajr** [comment]
> **Describe the bug** On our website A clear and concise description of what the bug is. On Jan Aman Website Footer bar Twitter logo are not same as per live Twitter site. **To reproduce** Please include a reproduction repository and outline the steps that are needed to run into the issue. On Website Footer bar this issue. **Expected behavior** Logo image change as per Twitter site logo. A clear and concise description of what you expected to happen. https://prnt.sc/iOZBI0j9sOHw :- See Screen Short
