### ISSUE TITLE
Validate commit messages

### ISSUE THREAD

**Issue by JobaDiniz** [amannn/action-semantic-pull-request#266]
**Is your feature request related to a problem? Please describe.**

Validating PR title is okay, but I think is more important to validate the commit messages themselves. Reading the documentation, it does not seem like this `action-semantic-pull-request` validates the commit messages.

**Describe the solution you'd like**

Also validate the PR commit messages.

**Comment by amannn** [comment]
Validating commit messages is out-of-scope for this action and not intended to be incorporated: https://github.com/amannn/action-semantic-pull-request/issues/234
