### ISSUE TITLE
Targeting wrong repo for status updates?

### ISSUE THREAD

**Issue by jsumners** [amannn/action-semantic-pull-request#28]
https://github.com/amannn/action-semantic-pull-request/blob/fc71bdaed6e918c444e480d7906f72c5b8a5e158/src/index.js#L42

Shouldn't the action update the status on the repository where the action was run?

**Comment by amannn** [comment]
The `target_url` is used for the details button of a check:

![Screenshot 2020-09-17 at 08 55 01](https://user-images.githubusercontent.com/4038316/93430854-962c0580-f8c3-11ea-95a1-dd279301ccf6.png)

If you click it, it should contain more details about what went wrong. In this case I'm linking to this repository, where someone who might not be familiar with the validation can get more information.

Is there something that you think could be improved here? I've just merged a PR that improves the README a bit (https://github.com/amannn/action-semantic-pull-request/pull/30).

**Comment by jsumners** [comment]
I can see that this is the same issue as #27 given your explanation. I'll close this one and continue the conversation there.
