### ISSUE TITLE
Support custom tags

### ISSUE THREAD

**Issue by alorma** [amannn/action-semantic-pull-request#39]
I've arrived to this repo from: https://github.com/zeke/semantic-pull-requests

As we are using GHE maybe we cannot use an app, but action looks great.

But, we use some tags that are not the ones defined on this action: `Feature`, `Fix`, Tech`...

Is possible to add the ability to allow tag customization?

<img width="800" alt="Captura de pantalla 2020-10-01 a las 10 24 22" src="https://user-images.githubusercontent.com/887462/94785683-47589280-03d0-11eb-9539-b235a19ee089.png">

**Comment by amannn** [comment]
@alorma Thanks for your feature request! This would definitely be interesting. Would you be interested in contributing this feature and make the current default configurable?

**Comment by amannn** [comment]
Cool! 🙂

This is the function that takes care of the validation:

https://github.com/amannn/action-semantic-pull-request/blob/a63cb11b8a036ceb4043853492574434cd097def/src/validatePrTitle.js#L5

I guess it should be possible to configure the supported prefixes from outside.

There are some tests, maybe that helps as a starting point: https://github.com/amannn/action-semantic-pull-request/blob/master/src/validatePrTitle.test.js.

Then we need to figure out how we can receive configuration from the YAML config of the Github action.

Maybe that helps as a first starting point!
