### ISSUE TITLE
Upon failure, report available options

### ISSUE THREAD

**Issue by abatilo** [amannn/action-semantic-pull-request#45]
When people are learning about conventional commits, they might not know all of the available options.

What might be really useful is that if there's a failure to match a conventional commit, to some how surface the list that's being checked against.

Some random ideas:
1. Leave a comment with all descriptions?
2. Leave a comment with a link to the [conventional-commit-types](https://github.com/commitizen/conventional-commit-types/blob/d1fb9cc953b8f1e33e2dd63babdf6ae8ab1c8711/index.json) file

**Comment by amannn** [comment]
Thanks for your feedback @abatilo.

Currently when the check fails, it looks like this:

<img width="848" alt="Screenshot 2020-10-13 at 08 28 05" src="https://user-images.githubusercontent.com/4038316/95823551-1bbd9c80-0d2e-11eb-853b-cfc4c0ef230d.png">

When you click on details, you'll see something like this:

<img width="987" alt="Screenshot 2020-10-13 at 08 29 05" src="https://user-images.githubusercontent.com/4038316/95823595-2f690300-0d2e-11eb-9bba-b59276ee9fd5.png">

Does that look reasonable to you?

E.g. when a test is failing, usually you don't want the CI job to comment on your PR with the failed test. Rather, the typical workflow is to click on details and to find out more there.

What do you think?

**Comment by abatilo** [comment]
I think that's really great!

I still think it would be nice to get more information for when to use each of the different types. Is there a way to add more information to that message, maybe?

**Comment by amannn** [comment]
What would you like to see in the message? We could include a link to https://www.conventionalcommits.org if that helps. At least as long as we don't have https://github.com/amannn/action-semantic-pull-request/issues/39.

Would you like to propose a better message in a PR?

**Comment by abatilo** [comment]
What would you think about just printing the raw output of `convenentional-commit-types`?

```
const conventionalCommitTypes = require("conventional-commit-types");
console.log(conventionalCommitTypes);
```

```
⇒  node index.js
{
  types: {
    feat: { description: 'A new feature', title: 'Features' },
    fix: { description: 'A bug fix', title: 'Bug Fixes' },
    docs: {
      description: 'Documentation only changes',
      title: 'Documentation'
    },
    style: {
      description: 'Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)',
      title: 'Styles'
    },
    refactor: {
      description: 'A code change that neither fixes a bug nor adds a feature',
      title: 'Code Refactoring'
    },
    perf: {
      description: 'A code change that improves performance',
      title: 'Performance Improvements'
    },
    test: {
      description: 'Adding missing tests or correcting existing tests',
      title: 'Tests'
    },
    build: {
      description: 'Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)',
      title: 'Builds'
    },
    ci: {
      description: 'Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)',
      title: 'Continuous Integrations'
    },
    chore: {
      description: "Other changes that don't modify src or test files",
      title: 'Chores'
    },
    revert: { description: 'Reverts a previous commit', title: 'Reverts' }
  }
}
```

**Comment by amannn** [comment]
I think I wouldn't just dump the object, but we could use it to format a list of bullet points with the prefix and the description. What do you think?

**Comment by abatilo** [comment]
I think that would be great too!

**Comment by amannn** [comment]
Added support for this in https://github.com/amannn/action-semantic-pull-request/pull/53 when you're using the default configuration.
