### ISSUE TITLE
deprecation notice

### ISSUE THREAD

**Issue by mrchief** [amannn/action-semantic-pull-request#62]
Noticed this in our logs with v2.1.0

```
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
```

I don't see this being directly anywhere in the `src` so probably coming from a dependency.

**Comment by amannn** [comment]
Thanks for the report! This has been fixed in [v2.1.1](https://github.com/amannn/action-semantic-pull-request/releases/tag/v2.1.1)
