### ISSUE TITLE
Can't use action-semantic-pull-request@v1.2.0 in workflow

### ISSUE THREAD

**Issue by Smityz** [amannn/action-semantic-pull-request#70]
Error info:

amannn/action-semantic-pull-request@v1.2.0 is not allowed to be used in apache/incubator-pegasus. Actions in this workflow must be: created by GitHub, verified in the GitHub Marketplace, within a repository owned by apache or match the following: apache/*, dawidd6/action-download-artifact@*, gradle/wrapper-validation-action@*, peaceiris/actions-gh-pages@*, peaceiris/actions-hugo@*, peter-evans/create-pull-request@*, scacap/action-surefire-report@*, shivammathur/setup-php@*, conda-incubator/setup-miniconda@*.

**Comment by amannn** [comment]
Hello @Smityz,

sorry, I'm not sure what's causing this message. It seems like you're using some kind of allowlist that forbids to use this action? If that's the case, please talk to your administrator about this.

I'm going to close this for now as I think it's not actionable, but please inquire again if you have evidence that this action is having an issue. A reproduction would also be helpful.

Thanks!
