### ISSUE TITLE
Something ain't right with pattern validation

### ISSUE THREAD

**Issue by derberg** [amannn/action-semantic-pull-request#80]
I did not investigate in details yet but I'm sure something is wrong. 
I have the following workflow https://github.com/derberg/test-experiment/blob/master/.github/workflows/testtest.yml
and it fails no matter if https://github.com/derberg/test-experiment/pull/67 is `ci: Test test` or `ci: test test`

**Comment by amannn** [comment]
Can you try to isolate the issue? As noted, I had to patch the code in https://github.com/amannn/action-semantic-pull-request/pull/79, as previously the validation would always fail, but it looks like you're using the latest version, right?

Some possible questions for isolating the issue:
- Does the workflow only fail when `subjectPatternError` is provided?
- Is something wrong with the regex?

**Comment by derberg** [comment]
this code logs Array with the paragraph as one array record

```
const paragraph = 'the quick brown fox jumps over the lazy dog. It barked.';
const regex = '^(?![A-Z]).+$';
const found = paragraph.match(regex);

console.log(found);
```

this code logs null
```
const paragraph = 'The quick brown fox jumps over the lazy dog. It barked.';
const regex = '^(?![A-Z]).+$';
const found = paragraph.match(regex);

console.log(found);
```

so the regex is good, this is the regex I use and it is exactly the same as the regex from readme. So it should trow error on CI if PR title starts with upper case.


so basically if the match is `null` then this part https://github.com/amannn/action-semantic-pull-request/blob/71a74e9d131e8d7c16cd672a42937ac88b1375db/src/validatePrTitle.js#L81-L85 should be applied, but only then

🤷🏼‍♂️ 

I'll do some manual tests, and if unit test like https://github.com/amannn/action-semantic-pull-request/blob/master/src/validatePrTitle.test.js#L111-L117 works, there must be something that can be found only manually

**Comment by derberg** [comment]
@amannn Hey, I just opened a PR with the fix
